python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame41_bonds.pdb --outdir analysis_results/results_1EEI/frame_41_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame56_bonds.pdb --outdir analysis_results/results_1EEI/frame_56_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame78_bonds.pdb --outdir analysis_results/results_1EEI/frame_78_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame52_bonds.pdb --outdir analysis_results/results_1EEI/frame_52_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame45_bonds.pdb --outdir analysis_results/results_1EEI/frame_45_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame8_bonds.pdb --outdir analysis_results/results_1EEI/frame_8_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame26_bonds.pdb --outdir analysis_results/results_1EEI/frame_26_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame31_bonds.pdb --outdir analysis_results/results_1EEI/frame_31_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame35_bonds.pdb --outdir analysis_results/results_1EEI/frame_35_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame88_bonds.pdb --outdir analysis_results/results_1EEI/frame_88_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame22_bonds.pdb --outdir analysis_results/results_1EEI/frame_22_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame32_bonds.pdb --outdir analysis_results/results_1EEI/frame_32_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame98_bonds.pdb --outdir analysis_results/results_1EEI/frame_98_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame25_bonds.pdb --outdir analysis_results/results_1EEI/frame_25_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame21_bonds.pdb --outdir analysis_results/results_1EEI/frame_21_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame36_bonds.pdb --outdir analysis_results/results_1EEI/frame_36_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame18_bonds.pdb --outdir analysis_results/results_1EEI/frame_18_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame55_bonds.pdb --outdir analysis_results/results_1EEI/frame_55_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame42_bonds.pdb --outdir analysis_results/results_1EEI/frame_42_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame46_bonds.pdb --outdir analysis_results/results_1EEI/frame_46_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame51_bonds.pdb --outdir analysis_results/results_1EEI/frame_51_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame68_bonds.pdb --outdir analysis_results/results_1EEI/frame_68_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame1_bonds.pdb --outdir analysis_results/results_1EEI/frame_1_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame62_bonds.pdb --outdir analysis_results/results_1EEI/frame_62_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame75_bonds.pdb --outdir analysis_results/results_1EEI/frame_75_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame5_bonds.pdb --outdir analysis_results/results_1EEI/frame_5_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame48_bonds.pdb --outdir analysis_results/results_1EEI/frame_48_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame71_bonds.pdb --outdir analysis_results/results_1EEI/frame_71_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame66_bonds.pdb --outdir analysis_results/results_1EEI/frame_66_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame81_bonds.pdb --outdir analysis_results/results_1EEI/frame_81_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame96_bonds.pdb --outdir analysis_results/results_1EEI/frame_96_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame12_bonds.pdb --outdir analysis_results/results_1EEI/frame_12_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame92_bonds.pdb --outdir analysis_results/results_1EEI/frame_92_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame85_bonds.pdb --outdir analysis_results/results_1EEI/frame_85_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame38_bonds.pdb --outdir analysis_results/results_1EEI/frame_38_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame16_bonds.pdb --outdir analysis_results/results_1EEI/frame_16_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame28_bonds.pdb --outdir analysis_results/results_1EEI/frame_28_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame95_bonds.pdb --outdir analysis_results/results_1EEI/frame_95_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame82_bonds.pdb --outdir analysis_results/results_1EEI/frame_82_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame11_bonds.pdb --outdir analysis_results/results_1EEI/frame_11_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame86_bonds.pdb --outdir analysis_results/results_1EEI/frame_86_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame91_bonds.pdb --outdir analysis_results/results_1EEI/frame_91_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame15_bonds.pdb --outdir analysis_results/results_1EEI/frame_15_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame2_bonds.pdb --outdir analysis_results/results_1EEI/frame_2_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame58_bonds.pdb --outdir analysis_results/results_1EEI/frame_58_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame76_bonds.pdb --outdir analysis_results/results_1EEI/frame_76_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame61_bonds.pdb --outdir analysis_results/results_1EEI/frame_61_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame6_bonds.pdb --outdir analysis_results/results_1EEI/frame_6_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame65_bonds.pdb --outdir analysis_results/results_1EEI/frame_65_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame72_bonds.pdb --outdir analysis_results/results_1EEI/frame_72_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame14_bonds.pdb --outdir analysis_results/results_1EEI/frame_14_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame90_bonds.pdb --outdir analysis_results/results_1EEI/frame_90_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame87_bonds.pdb --outdir analysis_results/results_1EEI/frame_87_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame10_bonds.pdb --outdir analysis_results/results_1EEI/frame_10_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame83_bonds.pdb --outdir analysis_results/results_1EEI/frame_83_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame94_bonds.pdb --outdir analysis_results/results_1EEI/frame_94_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame29_bonds.pdb --outdir analysis_results/results_1EEI/frame_29_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame73_bonds.pdb --outdir analysis_results/results_1EEI/frame_73_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame64_bonds.pdb --outdir analysis_results/results_1EEI/frame_64_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame7_bonds.pdb --outdir analysis_results/results_1EEI/frame_7_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame60_bonds.pdb --outdir analysis_results/results_1EEI/frame_60_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame77_bonds.pdb --outdir analysis_results/results_1EEI/frame_77_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame59_bonds.pdb --outdir analysis_results/results_1EEI/frame_59_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame3_bonds.pdb --outdir analysis_results/results_1EEI/frame_3_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame67_bonds.pdb --outdir analysis_results/results_1EEI/frame_67_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame70_bonds.pdb --outdir analysis_results/results_1EEI/frame_70_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame4_bonds.pdb --outdir analysis_results/results_1EEI/frame_4_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame49_bonds.pdb --outdir analysis_results/results_1EEI/frame_49_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame74_bonds.pdb --outdir analysis_results/results_1EEI/frame_74_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame63_bonds.pdb --outdir analysis_results/results_1EEI/frame_63_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame0_bonds.pdb --outdir analysis_results/results_1EEI/frame_0_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame17_bonds.pdb --outdir analysis_results/results_1EEI/frame_17_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame39_bonds.pdb --outdir analysis_results/results_1EEI/frame_39_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame84_bonds.pdb --outdir analysis_results/results_1EEI/frame_84_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame93_bonds.pdb --outdir analysis_results/results_1EEI/frame_93_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame13_bonds.pdb --outdir analysis_results/results_1EEI/frame_13_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame97_bonds.pdb --outdir analysis_results/results_1EEI/frame_97_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame80_bonds.pdb --outdir analysis_results/results_1EEI/frame_80_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame19_bonds.pdb --outdir analysis_results/results_1EEI/frame_19_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame37_bonds.pdb --outdir analysis_results/results_1EEI/frame_37_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame20_bonds.pdb --outdir analysis_results/results_1EEI/frame_20_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame24_bonds.pdb --outdir analysis_results/results_1EEI/frame_24_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame99_bonds.pdb --outdir analysis_results/results_1EEI/frame_99_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame33_bonds.pdb --outdir analysis_results/results_1EEI/frame_33_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame69_bonds.pdb --outdir analysis_results/results_1EEI/frame_69_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame50_bonds.pdb --outdir analysis_results/results_1EEI/frame_50_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame47_bonds.pdb --outdir analysis_results/results_1EEI/frame_47_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame43_bonds.pdb --outdir analysis_results/results_1EEI/frame_43_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame54_bonds.pdb --outdir analysis_results/results_1EEI/frame_54_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame44_bonds.pdb --outdir analysis_results/results_1EEI/frame_44_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame9_bonds.pdb --outdir analysis_results/results_1EEI/frame_9_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame53_bonds.pdb --outdir analysis_results/results_1EEI/frame_53_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame79_bonds.pdb --outdir analysis_results/results_1EEI/frame_79_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame57_bonds.pdb --outdir analysis_results/results_1EEI/frame_57_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame40_bonds.pdb --outdir analysis_results/results_1EEI/frame_40_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame23_bonds.pdb --outdir analysis_results/results_1EEI/frame_23_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame89_bonds.pdb --outdir analysis_results/results_1EEI/frame_89_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame34_bonds.pdb --outdir analysis_results/results_1EEI/frame_34_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame30_bonds.pdb --outdir analysis_results/results_1EEI/frame_30_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame27_bonds.pdb --outdir analysis_results/results_1EEI/frame_27_1EEI/ --ref_ligand X:517
