python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2q0u_1.pdb --outdir diffsbdd_analysis_results/2Q0U_results/ --ref_ligand A:401
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2fl6_1.pdb --outdir diffsbdd_analysis_results/2FL6_results/ --ref_ligand A:604
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2fl2_1.pdb --outdir diffsbdd_analysis_results/2FL2_results/ --ref_ligand B:605
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/5ncf_1.pdb --outdir diffsbdd_analysis_results/5NCF_results/ --ref_ligand A:201
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/3ukr_1.pdb --outdir diffsbdd_analysis_results/3UKR_results/ --ref_ligand B:401
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/3eks_1.pdb --outdir diffsbdd_analysis_results/3EKS_results/ --ref_ligand A:903
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/5ncp_1.pdb --outdir diffsbdd_analysis_results/5NCP_results/ --ref_ligand A:201
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2q2y_1.pdb --outdir diffsbdd_analysis_results/2Q2Y_results/ --ref_ligand A:604
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/5zzb_2.pdb --outdir diffsbdd_analysis_results/5ZZB_results/ --ref_ligand D:401
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/4pa0_2.pdb --outdir diffsbdd_analysis_results/4PA0_results/ --ref_ligand A:1101
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/3eku_1.pdb --outdir diffsbdd_analysis_results/3EKU_results/ --ref_ligand A:903
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/3mn5_1.pdb --outdir diffsbdd_analysis_results/3MN5_results/ --ref_ligand A:376
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/1j6z_1.pdb --outdir diffsbdd_analysis_results/1J6Z_results/ --ref_ligand A:1381
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/3k3b_3.pdb --outdir diffsbdd_analysis_results/3K3B_results/ --ref_ligand B:372
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/1q0b_2.pdb --outdir diffsbdd_analysis_results/1Q0B_results/ --ref_ligand B:605
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/5ndu_1.pdb --outdir diffsbdd_analysis_results/5NDU_results/ --ref_ligand A:201
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/1yrs_2.pdb --outdir diffsbdd_analysis_results/1YRS_results/ --ref_ligand A:604
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/5neg_1.pdb --outdir diffsbdd_analysis_results/5NEG_results/ --ref_ligand A:201
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/3l9h_1.pdb --outdir diffsbdd_analysis_results/3L9H_results/ --ref_ligand B:602
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2uym_2.pdb --outdir diffsbdd_analysis_results/2UYM_results/ --ref_ligand B:604
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/7aki_1.pdb --outdir diffsbdd_analysis_results/7AKI_results/ --ref_ligand A:202
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2fme_2.pdb --outdir diffsbdd_analysis_results/2FME_results/ --ref_ligand B:370
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/1esv_1.pdb --outdir diffsbdd_analysis_results/1ESV_results/ --ref_ligand A:401
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/6rcf_1.pdb --outdir diffsbdd_analysis_results/6RCF_results/ --ref_ligand A:201
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/1j78_1.pdb --outdir diffsbdd_analysis_results/1J78_results/ --ref_ligand B:500
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2gm1_3.pdb --outdir diffsbdd_analysis_results/2GM1_results/ --ref_ligand E:371
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/1dtl_1.pdb --outdir diffsbdd_analysis_results/1DTL_results/ --ref_ligand A:205
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2x7e_2.pdb --outdir diffsbdd_analysis_results/2X7E_results/ --ref_ligand B:1365
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/3cjo_2.pdb --outdir diffsbdd_analysis_results/3CJO_results/ --ref_ligand B:603
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/1sqk_1.pdb --outdir diffsbdd_analysis_results/1SQK_results/ --ref_ligand A:378
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/1rdw_1.pdb --outdir diffsbdd_analysis_results/1RDW_results/ --ref_ligand X:391
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/6g6y_1.pdb --outdir diffsbdd_analysis_results/6G6Y_results/ --ref_ligand A:403
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/5ncg_2.pdb --outdir diffsbdd_analysis_results/5NCG_results/ --ref_ligand B:201
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2a5x_1.pdb --outdir diffsbdd_analysis_results/2A5X_results/ --ref_ligand A:379
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/3ken_1.pdb --outdir diffsbdd_analysis_results/3KEN_results/ --ref_ligand A:370
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2pg2_1.pdb --outdir diffsbdd_analysis_results/2PG2_results/ --ref_ligand B:604
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2uyi_2.pdb --outdir diffsbdd_analysis_results/2UYI_results/ --ref_ligand B:604
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/6rcj_1.pdb --outdir diffsbdd_analysis_results/6RCJ_results/ --ref_ligand A:201
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile og_crystal_structs/2fky_2.pdb --outdir diffsbdd_analysis_results/2FKY_results/ --ref_ligand A:604
