python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame41.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_41_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame56.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_56_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame78.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_78_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame52.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_52_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame45.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_45_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame8.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_8_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame26.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_26_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame31.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_31_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame35.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_35_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame88.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_88_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame22.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_22_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame32.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_32_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame98.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_98_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame25.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_25_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame21.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_21_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame36.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_36_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame18.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_18_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame55.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_55_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame42.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_42_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame46.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_46_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame51.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_51_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame68.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_68_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame1.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_1_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame62.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_62_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame75.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_75_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame5.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_5_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame48.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_48_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame71.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_71_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame66.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_66_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame81.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_81_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame96.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_96_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame12.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_12_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame92.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_92_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame85.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_85_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame38.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_38_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame16.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_16_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame28.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_28_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame95.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_95_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame82.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_82_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame11.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_11_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame86.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_86_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame91.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_91_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame15.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_15_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame2.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_2_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame58.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_58_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame76.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_76_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame61.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_61_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame6.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_6_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame65.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_65_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame72.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_72_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame14.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_14_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame90.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_90_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame87.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_87_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame10.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_10_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame83.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_83_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame94.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_94_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame29.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_29_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame73.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_73_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame64.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_64_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame7.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_7_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame60.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_60_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame77.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_77_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame59.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_59_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame3.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_3_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame67.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_67_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame70.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_70_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame4.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_4_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame49.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_49_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame74.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_74_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame63.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_63_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame0.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_0_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame17.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_17_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame39.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_39_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame84.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_84_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame93.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_93_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame13.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_13_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame97.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_97_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame80.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_80_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame19.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_19_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame37.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_37_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame20.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_20_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame24.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_24_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame99.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_99_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame33.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_33_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame69.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_69_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame50.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_50_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame47.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_47_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame43.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_43_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame54.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_54_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame44.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_44_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame9.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_9_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame53.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_53_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame79.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_79_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame57.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_57_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame40.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_40_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame23.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_23_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame89.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_89_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame34.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_34_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame30.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_30_1EEI/ --ref_ligand X:517
python generate_ligands.py ckpt/moad_ca_cond.ckpt --pdbfile analysis_combined_pdbs/combined_1EEI/1EEI_MD_frame27.pdb_bonds.pdb --outdir analysis_results/results_1EEI/frame_27_1EEI/ --ref_ligand X:517
